[tool.poetry]
name = "taskonatorbot"
version = "0.1.0"
description = ""
authors = ["AmmoMax <steelratmax@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiogram = "^3.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
